const IS_DONE = 'IS_DONE'
const IS_ERR = 'IS_ERR'
const IS_FAIL = 'IS_FAIL'

// FAILS STATES
const USER_NOT_FOUND = 'USER_NOT_FOUND'

// ERRORS STATES
const REQUEST_ERROR = 'REQUEST_ERROR'

module.exports = {
  IS_DONE,
  IS_ERR,
  IS_FAIL,
  USER_NOT_FOUND,
  REQUEST_ERROR
}
