const IS_DONE = 'IS_DONE'
const IS_FAIL = 'IS_FAIL'

// FAILS STATES
const USER_NOT_FOUND = 'USER_NOT_FOUND'

// ERRORS STATES
const ERROR_REQUEST = 'ERROR_REQUEST'
const ERROR_PROCESS = 'ERROR_PROCESS'

// ERRORS MESSAGES
const ERROR_MESSAGE_DEFAULT = 'An error has been detected while trying to contact twitch API.'

// GLOBALS
const EVENTS_GLOBAL = 'EVENTS_GLOBALS'
const EVENTS_PAST = 'EVENTS_PAST'
const TWITCH_HASH_EVENT = '1ddc422675ea9d6e7659d54923633fede3a804bfec3b20e3df6ef8eea40d3ea1'
const TWITCH_HASH_DESC = '4fdc0f4f963f4b9ca046a0638dd5f96643708f49e129d437e48efb8d521cbaa4'

module.exports = {
  IS_DONE,
  IS_FAIL,
  USER_NOT_FOUND,
  ERROR_REQUEST,
  ERROR_PROCESS,
  ERROR_MESSAGE_DEFAULT,
  EVENTS_GLOBAL,
  EVENTS_PAST,
  TWITCH_HASH_EVENT,
  TWITCH_HASH_DESC
}
